### PR TITLE
fix: remove destroy and fix casings

### LINKED ISSUE #91: column "XXX_geom" of relation "XXX" does not exist
### Describe the bug
We are having some issues using your plugin. When trying to start for a large database, that has already several 100k entries, I'm running into this issue and I don't know, how to solve it - I can't see the column "XXX_geom" anywhere, so I was wondering, how exactly the plugin works.

```
error: 
          UPDATE pois
          SET ch_geo_points_geom = ST_SetSRID(ST_MakePoint(
              CAST((ch_geo_points::json->'lng')::text AS DOUBLE PRECISION),
              CAST((ch_geo_points::json->'lat')::text AS DOUBLE PRECISION)

          ), 4326)
          WHERE (ch_geo_points::json->'lng')::text != 'null' AND
                (ch_geo_points::json->'lat')::text != 'null'
           - column "ch_geo_points_geom" of relation "pois" does not exist
           - 
```

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

### PR DESCRIPTION
**Pull request by omikulcik**
- Removed redundant ts-ignores because they are not needed with the updated strapi-types library
- removed destroy procedure because it caused problems for larger databases and is not needed
- Unified casings because the bootstrap procedure was again crashing when capital letters were used

Closes #91

### CODE REVIEW

File: strapi-server.js [hunk 1]
```diff
@@ -1,3 +1,3 @@
 "use strict";
 //Change to "./dist/server" while developing
-module.exports = require("./server");
```
Comment (Ballonek) [inline strapi-server.js:3]: Prod mistake

**Review by Ballonek — APPROVED** [review]
Just /dist/server in strapi-server.js then approved :)
